[book]
title = "The Democracy We Deserve"
authors = ["Chris Borgia"]
language = "en"
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "light"
git-repository-url = "https://github.com/chrisb1011/democracy-we-deserve-book"
